export const START_PHOTOS_LOADING = "START_PHOTOS_LOADING";
export const STOP_PHOTOS_LOADING = "STOP_PHOTOS_LOADING";
export const SET_PHOTOS = "SET_PHOTOS";
export const SET_PHOTOS_ERROR = "SET_PHOTOS_ERROR";